base:
  project: house-dev
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/data.csv

load_data:
  raw_dataset_csv: data/raw/data.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.4
      l1_ratio: 0.12345
      
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib