base:
  project: house-dev
  random_state: 42
  target_col: SalePrice

data_source:
  s3_source: data_given/data.csv

load_data:
  raw_dataset_csv: data/raw/data.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  DecisionTreeRegressor:
    params:
      max_depth: 10
      min_samples_leaf: 2
      max_features: log2
      max_leaf_nodes: 20
      
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib